import json

questions = [
    "What courses are offered at Indian Institute of Technology Jammu?",
    "How can I apply for BTech admission?",
    "What is the eligibility for MTech admission?",
    "What is the admission procedure for PhD?",
    "What is the fee structure for BTech?",
    "What is the fee structure for MTech?",
    "What is the hostel fee at Indian Institute of Technology Jammu?",
    "Is hostel accommodation compulsory for first-year students?",
    "What are the cutoff marks for BTech admission?",
    "What are the GATE cutoff requirements for MTech?",
    "Can I apply for direct PhD after BTech?",
    "What scholarships are available for students?",
    "Does IIT Jammu provide financial assistance?",
    "What is the placement record of IIT Jammu?",
    "Which companies visit IIT Jammu for placements?",
    "What is the highest package offered at IIT Jammu?",
    "What is the average package for CSE students?",
    "Does IIT Jammu provide internship opportunities?",
    "How can I apply for internships through IIT Jammu?",
    "Which departments are available at IIT Jammu?",
    "What are the specializations in Computer Science?",
    "Is Artificial Intelligence available as a specialization?",
    "Does IIT Jammu offer Data Science courses?",
    "What research areas are available in CSE?",
    "Who is the director of IIT Jammu?",
    "Where is IIT Jammu located?",
    "What is the official contact email of IIT Jammu?",
    "How can I contact the admissions office?",
    "How can international students apply?",
    "What documents are required for admission?",
    "Is there any entrance exam for PhD admission?",
    "What is the last date for admission applications?",
    "When does the academic session start?",
    "What is the academic calendar for this semester?",
    "When are semester exams conducted?",
    "How does semester registration work?",
    "What is the grading system at IIT Jammu?",
    "What is the minimum CPI requirement?",
    "How can I get my transcript?",
    "What are the hostel facilities available?",
    "Are single rooms available in hostels?",
    "What are the mess charges?",
    "Does the campus have WiFi facilities?",
    "Are sports facilities available on campus?",
    "Is there a gym on campus?",
    "What medical facilities are available?",
    "Does IIT Jammu provide transport facilities?",
    "Is there a library on campus?",
    "What are the library timings?",
    "How can I access online journals and research papers?",
    "Who is Professor Badrinarayan Subuddhi?",
    "What are the research interests of Professor Badrinarayan Subuddhi?",
    "Which professors work on Machine Learning?",
    "Which faculty members work on Artificial Intelligence?",
    "Which professors work on robotics?",
    "Which faculty members work on cybersecurity?",
    "Which professors are working on NLP research?",
    "Which professors are working on computer vision?",
    "Which professors are accepting PhD students?",
    "How can I contact a professor for research collaboration?",
    "Which professor should I contact for AI research?",
    "What labs are available in the CSE department?",
    "Which labs are working on drone technology?",
    "Are there any ongoing AI projects at IIT Jammu?",
    "What funded research projects are currently active?",
    "Does IIT Jammu collaborate with industries for research?",
    "What are the latest research publications from IIT Jammu?",
    "Are there any startup incubation facilities?",
    "Does IIT Jammu support entrepreneurship?",
    "What clubs are available for students?",
    "Is there a coding club at IIT Jammu?",
    "What technical festivals are organized?",
    "When is the annual tech fest conducted?",
    "Are hackathons organized on campus?",
    "What are the latest events happening at IIT Jammu?",
    "Are there any upcoming AI workshops?",
    "How can I participate in seminars and conferences?",
    "Are there any internships currently open?",
    "What are the latest notices released by IIT Jammu?",
    "Where can I find the latest circulars?",
    "How can I apply for hostel leave?",
    "What are the hostel rules and regulations?",
    "What is the anti-ragging policy?",
    "How can I report technical issues on campus?",
    "Is there a student counseling facility available?",
    "What is the attendance policy?",
    "How can I change my branch?",
    "What are the eligibility criteria for branch change?",
    "Can students participate in exchange programs?",
    "Does IIT Jammu offer international collaborations?",
    "How can I join a research project as an undergraduate student?",
    "Which department is best for Machine Learning research?",
    "I completed BTech in Electronics. Can I apply for AI research?",
    "I want to pursue robotics research. Which professor should I contact?",
    "How can I prepare for MTech admission at IIT Jammu?",
    "Can I apply for multiple programs at IIT Jammu?",
    "What career opportunities are available after graduation?",
    "How can I stay updated with IIT Jammu announcements?",
    "Does IIT Jammu provide alumni networking opportunities?",
    "Why should I choose Indian Institute of Technology Jammu for higher studies?",
    "I have completed BTech in Electronics Engineering. Can I apply for direct PhD in AI or Machine Learning at Indian Institute of Technology Jammu?",
    "Which professors at Indian Institute of Technology Jammu are currently working on interdisciplinary AI and healthcare projects?",
    "I am interested in robotics and computer vision. Which department and faculty should I approach?",
    "Can you compare MTech in CSE and MTech in AI in terms of placements and research opportunities?",
    "Which faculty members are most suitable for research in sound detection and signal processing?",
    "I want to pursue research in cybersecurity but my background is Mechanical Engineering. Am I eligible?",
    "Which labs at IIT Jammu are actively working on funded AI research projects?",
    "How can I join an ongoing ML project as an undergraduate student?",
    "What are the current research trends at IIT Jammu in Artificial Intelligence?",
    "Which professors have published papers recently in NLP or Generative AI?",
    "I want to work on drone-based surveillance systems. Which research groups should I contact?",
    "Can you suggest faculty members whose interests match reinforcement learning and robotics?",
    "How can I approach a professor for research collaboration professionally?",
    "Which professors are currently accepting PhD scholars in AI-related fields?",
    "What are the chances of getting hostel accommodation after late admission confirmation?",
    "Can students from non-CS backgrounds pursue MTech in CSE-related specializations?",
    "How does IIT Jammu support startup incubation for AI-based projects?",
    "Which department is best for pursuing research in autonomous systems?",
    "What is the process for converting from MTech to PhD at IIT Jammu?",
    "Which faculty members collaborate with industries like DRDO, ISRO, or private AI companies?",
    "Are there any professors working on multimodal AI or speech recognition systems?",
    "Which labs provide GPU or high-performance computing facilities for deep learning research?",
    "I want to study AI but I am confused between CSE and Electrical Engineering research groups. Which should I choose?",
    "What are the minimum qualifications required for research assistant positions at IIT Jammu?",
    "Which research areas at IIT Jammu are expected to grow in the next 5 years?",
    "Can you recommend professors based on my interest in computer vision and medical imaging?",
    "How can I prepare for research internships under IIT Jammu professors?",
    "Which departments have the highest placement rates in recent years?",
    "Are there any interdisciplinary programs combining AI with Mechanical or Civil Engineering?",
    "How does IIT Jammu support students interested in entrepreneurship and startups?",
    "Which professors are working on embedded AI and edge computing systems?",
    "I want to pursue higher studies abroad after MTech. Which research groups would strengthen my profile?",
    "What research opportunities are available for first-year BTech students?",
    "Which faculty members focus on applied AI rather than theoretical AI?",
    "How can I access previous years’ placement statistics and recruiter data?",
    "Does IIT Jammu have collaborations with foreign universities for research exchange?",
    "Which professors are working on IoT and smart city technologies?",
    "What kind of projects do students usually work on during their final year?",
    "Which labs are open for undergraduate participation in research?",
    "How can I contribute to published research papers as a student?",
    "What are the most active student technical clubs related to AI and robotics?",
    "Which department offers the strongest curriculum for Machine Learning specialization?",
    "Can I pursue AI research without strong coding experience initially?",
    "Which professors work on ethical AI or explainable AI?",
    "How does IIT Jammu evaluate students for research assistantships?",
    "Are there any live industry-sponsored projects currently running on campus?",
    "What are the best pathways to enter AI research after completing BTech?",
    "Which faculty members have received major research grants recently?",
    "Can students from IIT Jammu participate in international hackathons and competitions?",
    "What facilities are available for students building robotics or AI hardware projects?",
    "Which professors are working on autonomous vehicles or smart transportation systems?",
    "I want to build a startup in AI during college. What support systems are available?",
    "Which faculty members specialize in data science and big data analytics?",
    "How does IIT Jammu support students preparing for higher studies abroad?",
    "Which professors are involved in cybersecurity and digital forensics research?",
    "Are there opportunities for interdisciplinary collaboration between departments?",
    "What kind of AI infrastructure does IIT Jammu provide for research students?",
    "Which labs are working on real-world industrial AI applications?",
    "How can I identify which professor aligns best with my research interests?",
    "Which current research areas have the highest funding opportunities at IIT Jammu?"
]

faqs = [{"q": q, "a": ""} for q in questions]

with open("faqs_template.json", "w", encoding="utf-8") as f:
    json.dump(faqs, f, indent=4)
